import javax.swing.*;
import java.io.File;
import java.awt.*;
import java.awt.event.*;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kuya mar
 */
public class AddRoom extends javax.swing.JFrame {
    List<File> uploadedFiles = new ArrayList<>();
    Connection con;
    int r5 = 0;
    private String username;
    /**
     * Creates new form AddRoom
     */
    public AddRoom(String username) {
        this.setIconImage(new ImageIcon("src/images/DorFiLogo.png").getImage());
        initComponents();
        this.username = username;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();
        addRoomBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        dormNameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        roomNumberField = new javax.swing.JTextField();
        roomTypeField = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        purokField = new javax.swing.JTextField();
        brgyField = new javax.swing.JTextField();
        municipalityField = new javax.swing.JTextField();
        provinceField = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        monthlyRentField = new javax.swing.JTextField();
        roomCapacityField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        roomRulesField = new javax.swing.JTextArea();
        jLabelPhoto = new javax.swing.JLabel();
        uploadBtn = new javax.swing.JButton();
        bedspaceField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        wifiAccess = new javax.swing.JCheckBox();
        studyArea = new javax.swing.JCheckBox();
        laundryRoom = new javax.swing.JCheckBox();
        diningArea = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        clearBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(72, 133, 199));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        backBtn.setBackground(new java.awt.Color(72, 133, 199));
        backBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backBtn.setText("< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        addRoomBtn.setBackground(new java.awt.Color(72, 133, 199));
        addRoomBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addRoomBtn.setText("Add Room");
        addRoomBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRoomBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Dormitory Name");

        dormNameField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Room Number");

        roomNumberField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        roomNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomNumberFieldActionPerformed(evt);
            }
        });

        roomTypeField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        roomTypeField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Room Type", "Male", "Female", "Mix" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Location");

        purokField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        purokField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purokFieldMouseClicked(evt);
            }
        });

        brgyField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        municipalityField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        municipalityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                municipalityFieldActionPerformed(evt);
            }
        });

        provinceField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        provinceField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Province", "Abra", "Nueva Ecija", "Bulacan", "Pampanga" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Room Details");

        monthlyRentField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        roomCapacityField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        roomRulesField.setColumns(20);
        roomRulesField.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        roomRulesField.setRows(5);
        jScrollPane1.setViewportView(roomRulesField);

        jLabelPhoto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPhoto.setText("Your selected photos: ");

        uploadBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        uploadBtn.setText("Upload Picture");
        uploadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadBtnActionPerformed(evt);
            }
        });

        bedspaceField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Facilities");

        wifiAccess.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        wifiAccess.setText("WiFi Access");

        studyArea.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        studyArea.setText("Study Area");

        laundryRoom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        laundryRoom.setText("Laundry Room");

        diningArea.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        diningArea.setText("Dining Area");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel7.setText("Add your Room");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText(" Room Rules");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Monthly Rent");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Room Capacity");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Available Bedspace/s");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Purok");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Barangay");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Municipality");

        clearBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(laundryRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(282, 282, 282)
                            .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(56, 56, 56)
                            .addComponent(addRoomBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(329, 329, 329)
                            .addComponent(jLabel7))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(monthlyRentField, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel9))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(roomCapacityField, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(bedspaceField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addGap(131, 131, 131)
                                                .addComponent(jLabel13))
                                            .addComponent(jLabel1))
                                        .addGap(182, 182, 182)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel14)
                                            .addComponent(roomNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(purokField)
                                        .addGap(18, 18, 18)
                                        .addComponent(brgyField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(dormNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 12, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(municipalityField, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(provinceField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(roomTypeField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(studyArea, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(diningArea, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(wifiAccess, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPhoto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(clearBtn)
                                .addGap(89, 89, 89))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(uploadBtn)
                                .addGap(54, 54, 54))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel7)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dormNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roomNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roomTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(purokField)
                    .addComponent(brgyField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(municipalityField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(provinceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jLabel9))
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(uploadBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clearBtn)
                        .addGap(3, 3, 3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(monthlyRentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roomCapacityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bedspaceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(wifiAccess)
                            .addComponent(laundryRoom))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(studyArea)
                            .addComponent(diningArea))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(addRoomBtn))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void uploadBtnActionPerformed(java.awt.event.ActionEvent evt) {                                          
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setMultiSelectionEnabled(true);

        int result = fileChooser.showOpenDialog(null);

        if (result == JFileChooser.APPROVE_OPTION) {

            File[] files = fileChooser.getSelectedFiles();

            // LOOP: prevent overwrite, add all new files
            for (File file : files) {
                uploadedFiles.add(file);
            }

            // Build display string (ALL PATHS)
            StringBuilder sb = new StringBuilder("<html>");

            for (File file : uploadedFiles) {
                sb.append(file.getAbsolutePath()).append("<br>");
            }

            sb.append("</html>");

            // Show only paths (NO IMAGE)
            jLabelPhoto.setText(sb.toString());
        }
    }                                         

    private void municipalityFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

    private void purokFieldMouseClicked(java.awt.event.MouseEvent evt) {                                        
        purokField.setText("");
    }                                       

    private void roomNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void addRoomBtnActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // ===== INPUT VALIDATION =====
        String validationError = validateInputs();
        if (validationError != null) {
            JOptionPane.showMessageDialog(this, validationError, "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String dormName = dormNameField.getText().trim();
        String roomNumber = roomNumberField.getText().trim();
        String roomType = roomTypeField.getSelectedItem().toString();
        String purok = purokField.getText().trim();
        String brgy = brgyField.getText().trim();
        String municipality = municipalityField.getText().trim();
        String province = provinceField.getSelectedItem().toString();
        int r4 = 0;

        String monthlyRent = monthlyRentField.getText().trim();
        double rent = Double.parseDouble(monthlyRent);

        String roomCapacity = roomCapacityField.getText().trim();
        String bedspace = bedspaceField.getText().trim();

        String roomRules = roomRulesField.getText().trim();

        try{
            con = MyConnection.getConnection();
            con.setAutoCommit(false);

            String locQuery = "INSERT INTO `location_table`(`purok`, `brgy`, `municipality`, `province`) VALUES (?,?,?,?)";
            PreparedStatement locPs = con.prepareStatement(locQuery, Statement.RETURN_GENERATED_KEYS);

            locPs.setString(1, purok);
            locPs.setString(2, brgy);
            locPs.setString(3, municipality);
            locPs.setString(4, province);

            int r1 = locPs.executeUpdate();

            ResultSet locRs = locPs.getGeneratedKeys();
            int locationId = 0;

            if (locRs.next()) {
                locationId = locRs.getInt(1);
            }

            String dormQuery = "INSERT INTO `dorm_building`(`username`, `location_id`, `dorm_name`) VALUES (?,?,?)";
            PreparedStatement dormPs = con.prepareStatement(dormQuery, Statement.RETURN_GENERATED_KEYS);

            dormPs.setString(1, username);
            dormPs.setInt(2, locationId);
            dormPs.setString(3, dormName);

            int r2 = dormPs.executeUpdate();

            ResultSet dormRs = dormPs.getGeneratedKeys();
            int dormId = 0;

            if (dormRs.next()) {
                dormId = dormRs.getInt(1);
            }

            String query = "INSERT INTO `room_table`(`username`, `room_number`, `r_type`, `rent`, `capacity`, `bedspace`,`room_rules`, `dorm_id`) VALUES (?,?,?,?,?,?,?,?)";
            PreparedStatement ps = con.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);

            ps.setString(1, username);
            ps.setString(2, roomNumber);
            ps.setString(3, roomType);
            ps.setDouble(4, rent);
            ps.setString(5, roomCapacity);
            ps.setString(6, bedspace);
            ps.setString(7, roomRules);
            ps.setInt(8, dormId);

            int r3 = ps.executeUpdate();

            ResultSet rs = ps.getGeneratedKeys();
            int roomId = 0;

            if (rs.next()) {
                roomId = rs.getInt(1);
            }

            String imgQuery = "INSERT INTO room_image (room_id, room_photo) VALUES (?, ?)";
            PreparedStatement imgPs = con.prepareStatement(imgQuery);

            for (File file : uploadedFiles) {
                imgPs.setInt(1, roomId);
                imgPs.setString(2, file.getAbsolutePath());
                r4 = imgPs.executeUpdate();
            }

            if (wifiAccess.isSelected()) {
                insertFacility(con, roomId, 1);
            }
            if (laundryRoom.isSelected()) {
                insertFacility(con, roomId, 2);
            }
            if (studyArea.isSelected()) {
                insertFacility(con, roomId, 3);
            }
            if (diningArea.isSelected()) {
                insertFacility(con, roomId, 4);
            }
            if (r1 > 0 && r2 > 0 && r3 > 0 && r4 > 0) {
                con.commit();

                locRs.close();
                locPs.close();

                dormRs.close();
                dormPs.close();

                rs.close();
                ps.close();

                imgPs.close();

                con.close();
                JOptionPane.showMessageDialog(null, "Room Added Successfully!");
                
                // Clear all fields after successful insertion
                clearAllFields();

            } else {
                con.rollback();
                JOptionPane.showMessageDialog(null, "Failed to add room");
            }

        }catch(Exception ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }                                          

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {                                        
        LandlordHomePage lhp = new LandlordHomePage(username);
        lhp.setVisible(true);
        lhp.pack();
        lhp.setLocationRelativeTo(null);
        lhp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }                                       

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {                                         
        uploadedFiles.clear();
        jLabelPhoto.setText("Your selected photos:");
        jLabelPhoto.repaint();
    }                                        

    public void insertFacility(Connection con, int roomId, int facilityId) throws SQLException {
        PreparedStatement fps = con.prepareStatement(
            "INSERT INTO room_facility (room_id, facility_id) VALUES (?, ?)"
        );
        fps.setInt(1, roomId);
        fps.setInt(2, facilityId);
        r5 = fps.executeUpdate();
    }

    /**
     * Validates all input fields
     * @return null if all inputs are valid, otherwise returns error message
     */
    private String validateInputs() {
        // Check Dorm Name
        if (dormNameField.getText().trim().isEmpty()) {
            return "Dormitory Name cannot be empty!";
        }

        // Check Room Number
        if (roomNumberField.getText().trim().isEmpty()) {
            return "Room Number cannot be empty!";
        }

        // Check Room Type
        if (roomTypeField.getSelectedIndex() == 0) {
            return "Please select a Room Type!";
        }

        // Check Purok
        if (purokField.getText().trim().isEmpty()) {
            return "Purok cannot be empty!";
        }

        // Check Barangay
        if (brgyField.getText().trim().isEmpty()) {
            return "Barangay cannot be empty!";
        }

        // Check Municipality
        if (municipalityField.getText().trim().isEmpty()) {
            return "Municipality cannot be empty!";
        }

        // Check Province
        if (provinceField.getSelectedIndex() == 0) {
            return "Please select a Province!";
        }

        // Check Monthly Rent - must not be empty and must be a valid number
        String rentText = monthlyRentField.getText().trim();
        if (rentText.isEmpty()) {
            return "Monthly Rent cannot be empty!";
        }
        if (!isValidNumber(rentText)) {
            return "Monthly Rent must be a valid number (no letters)!";
        }
        try {
            double rent = Double.parseDouble(rentText);
            if (rent <= 0) {
                return "Monthly Rent must be greater than 0!";
            }
        } catch (NumberFormatException e) {
            return "Monthly Rent must be a valid number!";
        }

        // Check Room Capacity - must not be empty and must be a valid integer
        String capacityText = roomCapacityField.getText().trim();
        if (capacityText.isEmpty()) {
            return "Room Capacity cannot be empty!";
        }
        if (!isValidInteger(capacityText)) {
            return "Room Capacity must be a valid whole number (no letters or decimals)!";
        }
        try {
            int capacity = Integer.parseInt(capacityText);
            if (capacity <= 0) {
                return "Room Capacity must be greater than 0!";
            }
        } catch (NumberFormatException e) {
            return "Room Capacity must be a valid number!";
        }

        // Check Available Bedspace - must not be empty and must be a valid integer
        String bedspaceText = bedspaceField.getText().trim();
        if (bedspaceText.isEmpty()) {
            return "Available Bedspace cannot be empty!";
        }
        if (!isValidInteger(bedspaceText)) {
            return "Available Bedspace must be a valid whole number (no letters or decimals)!";
        }
        try {
            int bedspace = Integer.parseInt(bedspaceText);
            if (bedspace <= 0) {
                return "Available Bedspace must be greater than 0!";
            }
        } catch (NumberFormatException e) {
            return "Available Bedspace must be a valid number!";
        }

        // Check if at least one picture is uploaded
        if (uploadedFiles.isEmpty()) {
            return "You must upload at least one picture!";
        }

        // Room Rules is optional - no validation needed
        // Facilities are optional - no validation needed

        return null; // All validations passed
    }

    /**
     * Checks if a string is a valid number (including decimals)
     */
    private boolean isValidNumber(String str) {
        try {
            Double.parseDouble(str);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    /**
     * Checks if a string is a valid integer
     */
    private boolean isValidInteger(String str) {
        try {
            Integer.parseInt(str);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    /**
     * Clears all form fields after successful insertion
     */
    private void clearAllFields() {
        dormNameField.setText("");
        roomNumberField.setText("");
        roomTypeField.setSelectedIndex(0);
        purokField.setText("");
        brgyField.setText("");
        municipalityField.setText("");
        provinceField.setSelectedIndex(0);
        monthlyRentField.setText("");
        roomCapacityField.setText("");
        bedspaceField.setText("");
        roomRulesField.setText("");
        wifiAccess.setSelected(false);
        studyArea.setSelected(false);
        laundryRoom.setSelected(false);
        diningArea.setSelected(false);
        uploadedFiles.clear();
        jLabelPhoto.setText("Your selected photos:");
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton addRoomBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField bedspaceField;
    private javax.swing.JTextField brgyField;
    private javax.swing.JButton clearBtn;
    private javax.swing.JCheckBox diningArea;
    private javax.swing.JTextField dormNameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelPhoto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox laundryRoom;
    private javax.swing.JTextField monthlyRentField;
    private javax.swing.JTextField municipalityField;
    private javax.swing.JComboBox<String> provinceField;
    private javax.swing.JTextField purokField;
    private javax.swing.JTextField roomCapacityField;
    private javax.swing.JTextField roomNumberField;
    private javax.swing.JTextArea roomRulesField;
    private javax.swing.JComboBox<String> roomTypeField;
    private javax.swing.JCheckBox studyArea;
    private javax.swing.JButton uploadBtn;
    private javax.swing.JCheckBox wifiAccess;
    // End of variables declaration                   
}
