import javax.swing.*;
import java.io.File;
import java.awt.*;
import java.awt.event.*;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kuya mar
 */
public class AddRoom extends javax.swing.JFrame {
    List<File> uploadedFiles = new ArrayList<>();
    Connection con;
    int r5 = 0;
    private String username;
    /**
     * Creates new form AddRoom
     */
    public AddRoom(String username) {
        
        initComponents();
        this.username = username;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();
        addRoomBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        dormNameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        roomNumberField = new javax.swing.JTextField();
        roomTypeField = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        purokField = new javax.swing.JTextField();
        brgyField = new javax.swing.JTextField();
        municipalityField = new javax.swing.JTextField();
        provinceField = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        monthlyRentField = new javax.swing.JTextField();
        roomCapacityField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        roomRulesField = new javax.swing.JTextArea();
        jLabelPhoto = new javax.swing.JLabel();
        uploadBtn = new javax.swing.JButton();
        lotNumberField = new javax.swing.JTextField();
        bedspaceField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        wifiAccess = new javax.swing.JCheckBox();
        studyArea = new javax.swing.JCheckBox();
        laundryRoom = new javax.swing.JCheckBox();
        diningArea = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(72, 133, 199));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText(" DorFi");

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        backBtn.setBackground(new java.awt.Color(72, 133, 199));
        backBtn.setText("< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        addRoomBtn.setBackground(new java.awt.Color(72, 133, 199));
        addRoomBtn.setText("Add Room");
        addRoomBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRoomBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Dormitory Name");

        jLabel3.setText("Room Number");

        roomTypeField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Room Type", "Male", "Female", "Mix" }));

        jLabel4.setText("Location");

        purokField.setText("Purok");
        purokField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purokFieldMouseClicked(evt);
            }
        });

        brgyField.setText("Barangay");

        municipalityField.setText("Municipality");

        provinceField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Province", "Abra", "Nueva Ecija", "Bulacan", "Pampanga" }));

        jLabel5.setText("Room Details");

        monthlyRentField.setText("Monthly Rent");

        roomCapacityField.setText("Room Capacity");

        roomRulesField.setColumns(20);
        roomRulesField.setRows(5);
        roomRulesField.setText("Room Rules\n");
        jScrollPane1.setViewportView(roomRulesField);

        jLabelPhoto.setText("Your selected photos(MAX 3): ");

        uploadBtn.setText("Upload Picture");
        uploadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadBtnActionPerformed(evt);
            }
        });

        lotNumberField.setText("Lot no.");
        lotNumberField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lotNumberFieldMouseClicked(evt);
            }
        });

        bedspaceField.setText("Available Bedspace/s ");

        jLabel6.setText("Facilities");

        wifiAccess.setText("WiFi Access");

        studyArea.setText("Study Area");

        laundryRoom.setText("Laundry Room");

        diningArea.setText("Dining Area");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(monthlyRentField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(roomCapacityField))
                                .addComponent(dormNameField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(wifiAccess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(studyArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(diningArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(laundryRoom, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(lotNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(purokField, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(21, 21, 21)
                                            .addComponent(brgyField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addComponent(jLabel6))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(roomNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(roomTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(uploadBtn))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel3)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(municipalityField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(provinceField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(bedspaceField))
                                        .addGap(0, 17, Short.MAX_VALUE)))
                                .addContainerGap())))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(addRoomBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dormNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roomNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roomTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(purokField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brgyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(municipalityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(provinceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lotNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monthlyRentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roomCapacityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bedspaceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(wifiAccess)
                            .addComponent(laundryRoom))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(studyArea)
                            .addComponent(diningArea))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(uploadBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(addRoomBtn))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void insertFacility(Connection con, int roomId, int facilityId) throws SQLException {
    PreparedStatement fps = con.prepareStatement(
        "INSERT INTO room_facility (room_id, facility_id) VALUES (?, ?)"
    );
    fps.setInt(1, roomId);
    fps.setInt(2, facilityId);
    r5 = fps.executeUpdate();
}
    private void addRoomBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRoomBtnActionPerformed
        String dormName = dormNameField.getText().trim();
        String roomNumber = roomNumberField.getText().trim();
        String roomType = roomTypeField.getSelectedItem().toString();
        String lotNumber = lotNumberField.getText().trim();
        String purok = purokField.getText().trim();
        String brgy = brgyField.getText().trim();
        String municipality = municipalityField.getText().trim();
        String province = provinceField.getSelectedItem().toString();
        int r4 = 0;
        
        String monthlyRent = monthlyRentField.getText().trim();
        double rent = Double.parseDouble(monthlyRent);
        
        String roomCapacity = roomCapacityField.getText().trim();
        String bedspace = bedspaceField.getText().trim();
        
        String roomRules = roomRulesField.getText().trim();
        
        
        
        
        try{
            con = MyConnection.getConnection();
            con.setAutoCommit(false);
            
            String locQuery = "INSERT INTO `location_table`(`purok`, `brgy`, `municipality`, `province`) VALUES (?,?,?,?)";
            PreparedStatement locPs = con.prepareStatement(locQuery, Statement.RETURN_GENERATED_KEYS);
            
            locPs.setString(1, purok);
            locPs.setString(2, brgy);
            locPs.setString(3, municipality);
            locPs.setString(4, province);
            
            int r1 = locPs.executeUpdate();
            
            ResultSet locRs = locPs.getGeneratedKeys();
            int locationId = 0;
            
            if (locRs.next()) {
            locationId = locRs.getInt(1);
            }
            
            String dormQuery = "INSERT INTO `dorm_building`(`username`, `location_id`, `dorm_name`) VALUES (?,?,?)";
            PreparedStatement dormPs = con.prepareStatement(dormQuery, Statement.RETURN_GENERATED_KEYS);
            
            dormPs.setString(1, username);
            dormPs.setInt(2, locationId);
            dormPs.setString(3, dormName);
            
            int r2 = dormPs.executeUpdate();
            
            ResultSet dormRs = dormPs.getGeneratedKeys();
            int dormId = 0;
            
            if (dormRs.next()) {
            dormId = dormRs.getInt(1);
            }
            
            String query = "INSERT INTO `room_table`(`username`, `room_number`, `r_type`, `rent`, `capacity`, `bedspace`,`room_rules`, `dorm_id`) VALUES (?,?,?,?,?,?,?,?)";
            PreparedStatement ps = con.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);
            
            ps.setString(1, username);
            ps.setString(2, roomNumber);
            ps.setString(3, roomType);
            ps.setDouble(4, rent);
            ps.setString(5, roomCapacity);
            ps.setString(6, bedspace);
            ps.setString(7, roomRules);
            ps.setInt(8, dormId);

            int r3 = ps.executeUpdate();
            
            ResultSet rs = ps.getGeneratedKeys();
            int roomId = 0;
            
            if (rs.next()) {
            roomId = rs.getInt(1);
            }
            
            String imgQuery = "INSERT INTO room_image (room_id, room_photo) VALUES (?, ?)";
    PreparedStatement imgPs = con.prepareStatement(imgQuery);

    for (File file : uploadedFiles) {
        imgPs.setInt(1, roomId);
        imgPs.setString(2, file.getAbsolutePath());
        r4 = imgPs.executeUpdate();
    }
            
            if (wifiAccess.isSelected()) {
                insertFacility(con, roomId, 1);
            }
            if (laundryRoom.isSelected()) {
                insertFacility(con, roomId, 2);
            }
            if (studyArea.isSelected()) {
                insertFacility(con, roomId, 3);
            }
            if (diningArea.isSelected()) {
                insertFacility(con, roomId, 4);
            }
            if (r1 > 0 && r2 > 0 && r3 > 0 && r4 > 0 && r5 > 0) {
            con.commit();
            con.commit();
            
            locRs.close();
            locPs.close();

            dormRs.close();
            dormPs.close();

            rs.close();
            ps.close();

            imgPs.close();

            con.close();
            JOptionPane.showMessageDialog(null, "Account created");

            
            

        } else {
            con.rollback();
            JOptionPane.showMessageDialog(null, "Failed to create account");
        }
            
        }catch(Exception ex){
            ex.printStackTrace();
            
        }

    }//GEN-LAST:event_addRoomBtnActionPerformed

    private void uploadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadBtnActionPerformed
        JFileChooser fileChooser = new JFileChooser();
fileChooser.setMultiSelectionEnabled(true);

int result = fileChooser.showOpenDialog(null);

if (result == JFileChooser.APPROVE_OPTION) {

    File[] files = fileChooser.getSelectedFiles();

    // LOOP: prevent overwrite, add all new files
    for (File file : files) {
        uploadedFiles.add(file);
    }

    // Build display string (ALL PATHS)
    StringBuilder sb = new StringBuilder("<html>");

    for (File file : uploadedFiles) {
        sb.append(file.getAbsolutePath()).append("<br>");
    }

    sb.append("</html>");

    // Show only paths (NO IMAGE)
    jLabelPhoto.setText(sb.toString());
}
    }//GEN-LAST:event_uploadBtnActionPerformed

    private void lotNumberFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lotNumberFieldMouseClicked
        lotNumberField.setText("");
    }//GEN-LAST:event_lotNumberFieldMouseClicked

    private void purokFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purokFieldMouseClicked
        purokField.setText("");
    }//GEN-LAST:event_purokFieldMouseClicked

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        LandlordHomePage lhp = new LandlordHomePage(username);
        lhp.setVisible(true);
        lhp.pack();
        lhp.setLocationRelativeTo(null);
        lhp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRoomBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField bedspaceField;
    private javax.swing.JTextField brgyField;
    private javax.swing.JCheckBox diningArea;
    private javax.swing.JTextField dormNameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelPhoto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox laundryRoom;
    private javax.swing.JTextField lotNumberField;
    private javax.swing.JTextField monthlyRentField;
    private javax.swing.JTextField municipalityField;
    private javax.swing.JComboBox<String> provinceField;
    private javax.swing.JTextField purokField;
    private javax.swing.JTextField roomCapacityField;
    private javax.swing.JTextField roomNumberField;
    private javax.swing.JTextArea roomRulesField;
    private javax.swing.JComboBox<String> roomTypeField;
    private javax.swing.JCheckBox studyArea;
    private javax.swing.JButton uploadBtn;
    private javax.swing.JCheckBox wifiAccess;
    // End of variables declaration//GEN-END:variables
}
