import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kuya mar
 */
public class LandlordHomePage extends javax.swing.JFrame {
    private String username;
    Connection con;
    private int currentPage = 1;
private int roomsPerPage = 3;
private java.util.List<Object[]> roomList = new java.util.ArrayList<>();
    /**
     * Creates new form LandlordHomePage
     */
    public LandlordHomePage(String username) {
        initComponents();
        setSize(900, 670); 
        setResizable(false);
        this.username = username;
        con = MyConnection.getConnection();
    
        dormPanel.setLayout(new GridLayout(2, 2, 10, 10));
        roomManagementPanel.setLayout(new GridLayout(2, 2, 10, 10));
        roomManagementPanel.setPreferredSize(null);
        CardLayout cl = (CardLayout) parentPanel.getLayout();

// 💥 Clear the wrong NetBeans cards
parentPanel.removeAll();

// 💥 Re-add with correct names
parentPanel.add(dormPanel, "dorm");
parentPanel.add(roomManagementPanel, "manageRoom");
parentPanel.add(accountSettingPanel, "account");
parentPanel.add(infoPanel, "info");


// 💥 Show default panel
cl.show(parentPanel, "manageRoom");

parentPanel.revalidate();
parentPanel.repaint();
        loadName();
        displayRoom();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        landlordName4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        dormitoriesBtn4 = new javax.swing.JButton();
        manageRoomBtn4 = new javax.swing.JButton();
        accountSettingsBtn4 = new javax.swing.JButton();
        logoutBtn4 = new javax.swing.JButton();
        addAccountBtn4 = new javax.swing.JButton();
        informationBtn4 = new javax.swing.JButton();
        parentPanel = new javax.swing.JPanel();
        dormPanel = new javax.swing.JPanel();
        accountSettingPanel = new javax.swing.JPanel();
        infoPanel = new javax.swing.JPanel();
        roomManagementPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(720, 615));
        setSize(new java.awt.Dimension(700, 615));

        jPanel1.setBackground(new java.awt.Color(72, 133, 199));

        jPanel11.setBackground(new java.awt.Color(153, 204, 255));

        landlordName4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        landlordName4.setText("0");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText(" DorFi");

        dormitoriesBtn4.setForeground(new java.awt.Color(0, 153, 204));
        dormitoriesBtn4.setText("View Dormitories");
        dormitoriesBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dormitoriesBtn4ActionPerformed(evt);
            }
        });

        manageRoomBtn4.setForeground(new java.awt.Color(0, 153, 204));
        manageRoomBtn4.setText("Manage Room");
        manageRoomBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageRoomBtn4ActionPerformed(evt);
            }
        });

        accountSettingsBtn4.setForeground(new java.awt.Color(0, 153, 204));
        accountSettingsBtn4.setText("Account Settings");
        accountSettingsBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountSettingsBtn4ActionPerformed(evt);
            }
        });

        logoutBtn4.setBackground(new java.awt.Color(72, 133, 199));
        logoutBtn4.setForeground(new java.awt.Color(255, 255, 255));
        logoutBtn4.setText("Log-out");
        logoutBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtn4ActionPerformed(evt);
            }
        });

        addAccountBtn4.setForeground(new java.awt.Color(0, 153, 204));
        addAccountBtn4.setText("Add another account");
        addAccountBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAccountBtn4ActionPerformed(evt);
            }
        });

        informationBtn4.setForeground(new java.awt.Color(0, 153, 204));
        informationBtn4.setText("My Information");
        informationBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informationBtn4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(informationBtn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(landlordName4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dormitoriesBtn4, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(manageRoomBtn4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(accountSettingsBtn4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(logoutBtn4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(addAccountBtn4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(landlordName4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(informationBtn4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dormitoriesBtn4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageRoomBtn4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accountSettingsBtn4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutBtn4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addAccountBtn4)
                .addGap(31, 31, 31))
        );

        parentPanel.setBackground(new java.awt.Color(153, 204, 255));
        parentPanel.setPreferredSize(new java.awt.Dimension(472, 560));
        parentPanel.setLayout(new java.awt.CardLayout());

        dormPanel.setBackground(new java.awt.Color(153, 204, 255));
        dormPanel.setPreferredSize(new java.awt.Dimension(452, 477));

        javax.swing.GroupLayout dormPanelLayout = new javax.swing.GroupLayout(dormPanel);
        dormPanel.setLayout(dormPanelLayout);
        dormPanelLayout.setHorizontalGroup(
            dormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );
        dormPanelLayout.setVerticalGroup(
            dormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        parentPanel.add(dormPanel, "card6");

        accountSettingPanel.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout accountSettingPanelLayout = new javax.swing.GroupLayout(accountSettingPanel);
        accountSettingPanel.setLayout(accountSettingPanelLayout);
        accountSettingPanelLayout.setHorizontalGroup(
            accountSettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );
        accountSettingPanelLayout.setVerticalGroup(
            accountSettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        parentPanel.add(accountSettingPanel, "card5");

        infoPanel.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        parentPanel.add(infoPanel, "card3");

        roomManagementPanel.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout roomManagementPanelLayout = new javax.swing.GroupLayout(roomManagementPanel);
        roomManagementPanel.setLayout(roomManagementPanelLayout);
        roomManagementPanelLayout.setHorizontalGroup(
            roomManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );
        roomManagementPanelLayout.setVerticalGroup(
            roomManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        parentPanel.add(roomManagementPanel, "card6");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(parentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(parentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dormitoriesBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dormitoriesBtn4ActionPerformed
        CardLayout cl = (CardLayout) parentPanel.getLayout();
        cl.show(parentPanel, "dorm");
        showDormPage(1);
        resetMenuButtons();
        highlightButton(dormitoriesBtn4);
    }//GEN-LAST:event_dormitoriesBtn4ActionPerformed

    private void informationBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informationBtn4ActionPerformed
        CardLayout cl = (CardLayout) parentPanel.getLayout();
        cl.show(parentPanel, "info");
        resetMenuButtons();
        highlightButton(informationBtn4);
    }//GEN-LAST:event_informationBtn4ActionPerformed

    private void manageRoomBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageRoomBtn4ActionPerformed
        CardLayout cl = (CardLayout) parentPanel.getLayout();
        cl.show(parentPanel, "manageRoom");
        resetMenuButtons();
        highlightButton(manageRoomBtn4);
    }//GEN-LAST:event_manageRoomBtn4ActionPerformed

    private void accountSettingsBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountSettingsBtn4ActionPerformed
        CardLayout cl = (CardLayout) parentPanel.getLayout();
        cl.show(parentPanel, "account");
        resetMenuButtons();
        highlightButton(accountSettingsBtn4);
    }//GEN-LAST:event_accountSettingsBtn4ActionPerformed

    private void logoutBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtn4ActionPerformed
        landlordLogin landlog = new landlordLogin();
        landlog.setVisible(true);
        landlog.pack();
        landlog.setLocationRelativeTo(null);
        landlog.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_logoutBtn4ActionPerformed

    private void addAccountBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAccountBtn4ActionPerformed
        CreateAccountLandlord cal = new CreateAccountLandlord();
        cal.setVisible(true);
        cal.pack();
        cal.setLocationRelativeTo(null);
        cal.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_addAccountBtn4ActionPerformed
     private void highlightButton(JButton btn) {
    btn.setBackground(new Color(72, 133, 199)); // same as theme
    btn.setForeground(Color.WHITE);
}
     private void resetMenuButtons() {
    Color defaultColor = new Color(0, 153, 204);
    Color defaultBackColor = new Color(240,240,240);
    informationBtn4.setBackground(defaultBackColor);
    dormitoriesBtn4.setBackground(defaultBackColor);
    manageRoomBtn4.setBackground(defaultBackColor);
    accountSettingsBtn4.setBackground(defaultBackColor);

    informationBtn4.setForeground(defaultColor);
    dormitoriesBtn4.setForeground(defaultColor);
    manageRoomBtn4.setForeground(defaultColor);
    accountSettingsBtn4.setForeground(defaultColor);
}
    private void loadName() {
    String query = "SELECT first_name FROM landlord_profile WHERE username = ?";

    try (Connection con = MyConnection.getConnection();
         PreparedStatement ps = con.prepareStatement(query)) {

        ps.setString(1, username);

        ResultSet rs = ps.executeQuery();
        
        roomManagementPanel.removeAll();


        roomManagementPanel.add(createAddRoomCard());

        if (rs.next()) {
            landlordName4.setText(rs.getString("first_name")); // ✅ direct
        } else {
            landlordName4.setText("No records");
        }

    } catch (SQLException ex) {
        ex.printStackTrace();
    }
}
   
    private void displayRoom() {
    roomList.clear();

    try {
        String query = "SELECT r.room_id, r.room_number, r.rent, d.dorm_name, l.brgy, l.municipality , l.location_id, d.dorm_id " +
    "FROM room_table r " +
    "JOIN dorm_building d ON r.dorm_id = d.dorm_id " +
    "JOIN location_table l ON d.location_id = l.location_id " +
    "WHERE r.username = ?";

        PreparedStatement ps = con.prepareStatement(query);
        ps.setString(1, username);
        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            roomList.add(new Object[]{
                rs.getInt("room_id"),
                rs.getString("room_number"),
                rs.getString("dorm_name"),
                rs.getDouble("rent"),
                rs.getString("brgy"),
                rs.getString("municipality"),
                rs.getInt("location_id"),
                rs.getInt("dorm_id")
            });
        }

    } catch (SQLException e) {
        e.printStackTrace();
    }

    showPage(1); // start at page 1
}
   private void showPage(int page) {
    roomManagementPanel.removeAll();

    currentPage = page;

    // 💥 STEP 1: change layout of main panel
    roomManagementPanel.setLayout(new BorderLayout());

    // 💥 STEP 2: create grid panel (this replaces your direct adds)
    JPanel gridPanel = new JPanel(new GridLayout(2, 2, 12, 12));
    gridPanel.setBackground(new Color(153, 204, 255));
    gridPanel.setOpaque(true);
    
    gridPanel.setBorder(BorderFactory.createEmptyBorder(12, 12, 12, 12));
    // ✅ ADD ROOM CARD FIRST
    gridPanel.add(createAddRoomCard());

    int start = (page - 1) * roomsPerPage;
    int end = Math.min(start + roomsPerPage, roomList.size());

    for (int i = start; i < end; i++) {
        Object[] data = roomList.get(i);

        int id = (int) data[0];
        String roomNo = (String) data[1];
        String dorm = (String) data[2];
        double rent = (double) data[3];
        String brgy = (String) data[4];
        String municipality = (String) data[5];
        int locationId = (int) data[6];
        int dormId = (int) data[7];

        // 💥 ADD TO GRID PANEL (NOT roomManagementPanel)
        gridPanel.add(createManageRoomCard(id, roomNo, dorm, rent, brgy, municipality,locationId,dormId));
    }

    // 💥 STEP 3: pagination panel (BOTTOM)
    JPanel navPanel = new JPanel();

    JButton prev = new JButton("Previous");
    JButton next = new JButton("Next");

    prev.setEnabled(page > 1);
    next.setEnabled(end < roomList.size());

    prev.addActionListener(e -> showPage(currentPage - 1));
    next.addActionListener(e -> showPage(currentPage + 1));

    navPanel.add(prev);
    navPanel.add(next);

    // 💥 STEP 4: add properly using BorderLayout
    roomManagementPanel.add(gridPanel, BorderLayout.CENTER);
    roomManagementPanel.add(navPanel, BorderLayout.SOUTH);

    roomManagementPanel.revalidate();
    roomManagementPanel.repaint();
}
      
       
    private ImageIcon getFirstImage(int roomId) {
    try {
        String q = "SELECT room_photo FROM room_image WHERE room_id = ? LIMIT 1";
        PreparedStatement ps = con.prepareStatement(q);
        ps.setInt(1, roomId);

        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            String path = rs.getString("room_photo");
            return new ImageIcon(path);
        }

    } catch (Exception e) {
        e.printStackTrace();
    }
    return null;
}
private void deleteRecord(int roomId, int dormId, int locationId, Connection con) {
     try {
        con.setAutoCommit(false);

        // 🔥 delete child tables first
        PreparedStatement ps;

        ps = con.prepareStatement("DELETE FROM room_image WHERE room_id = ?");
        ps.setInt(1, roomId);
        ps.executeUpdate();
        ps.close();

        ps = con.prepareStatement("DELETE FROM room_facility WHERE room_id = ?");
        ps.setInt(1, roomId);
        ps.executeUpdate();
        ps.close();

        // 🔥 delete room
        ps = con.prepareStatement("DELETE FROM room_table WHERE room_id = ?");
        ps.setInt(1, roomId);
        ps.executeUpdate();
        ps.close();

        // ⚠️ ONLY delete dorm if no more rooms exist
        ps = con.prepareStatement("SELECT COUNT(*) FROM room_table WHERE dorm_id = ?");
        ps.setInt(1, dormId);
        ResultSet rs = ps.executeQuery();

        if (rs.next() && rs.getInt(1) == 0) {
            ps = con.prepareStatement("DELETE FROM dorm_building WHERE dorm_id = ?");
            ps.setInt(1, dormId);
            ps.executeUpdate();
            ps.close();

            // ⚠️ ONLY delete location if no more dorms exist
            ps = con.prepareStatement("SELECT COUNT(*) FROM dorm_building WHERE location_id = ?");
            ps.setInt(1, locationId);
            rs = ps.executeQuery();

            if (rs.next() && rs.getInt(1) == 0) {
                ps = con.prepareStatement("DELETE FROM location_table WHERE location_id = ?");
                ps.setInt(1, locationId);
                ps.executeUpdate();
                ps.close();
            }
        }

        con.commit();

    } catch (SQLException ex) {
        try {
            con.rollback();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        ex.printStackTrace();
    } finally {
        try {
            con.setAutoCommit(true);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
}
private void deleteRoomCard(int roomId, int dormId, int locationId) {
    int option = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to delete this record?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION
    );

    if (option == JOptionPane.YES_OPTION) {
        // 🔥 Delete from database
        deleteRecord(roomId, dormId, locationId, con);

        // 🔥 Remove from local list (VERY IMPORTANT)
        roomList.removeIf(room -> (int) room[0] == roomId);

        JOptionPane.showMessageDialog(this, "Record deleted successfully.");

        // 🔥 Refresh UI (stay on same page if possible)
        int maxPage = (int) Math.ceil((double) roomList.size() / roomsPerPage);
        if (currentPage > maxPage) {
            currentPage = Math.max(1, maxPage);
        }

        showPage(currentPage);
    }
}
    private JPanel createManageRoomCard(int roomId, String roomNo, String dormName, double rent, String brgy, String municipality, int locationId, int dormId) {
    JPanel panel = new JPanel();
    panel.setPreferredSize(new Dimension(220, 220));
    panel.setLayout(new BorderLayout());
    panel.setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY));
    panel.setBackground(Color.WHITE);

    int cardWidth = 180;
    int cardHeight = 200;
    int imageWidth = 224;
    int imageHeight = (int)(cardHeight * 0.7);


    // 🔷 IMAGE
    JLabel imgLabel = new JLabel();
    imgLabel.setHorizontalAlignment(JLabel.CENTER);

    ImageIcon img = getFirstImage(roomId);
    if (img != null) {
        Image scaled = img.getImage().getScaledInstance(imageWidth, imageHeight, Image.SCALE_SMOOTH);
        imgLabel.setIcon(new ImageIcon(scaled));
    }
    imgLabel.setPreferredSize(new Dimension(cardWidth, imageHeight));
    panel.add(imgLabel, BorderLayout.NORTH);

    // 🔷 INFO SECTION (VERTICAL)
    JPanel infoPanel = new JPanel();
    infoPanel.setLayout(new BoxLayout(infoPanel, BoxLayout.Y_AXIS));
    infoPanel.setBackground(Color.WHITE);
    infoPanel.setBorder(BorderFactory.createEmptyBorder(5, 10, 5, 10));

    JLabel title = new JLabel("Room " + roomNo + ", " + dormName);
    title.setFont(new Font("Arial", Font.BOLD, 13));

    JLabel location = new JLabel(brgy + ", " + municipality);
    location.setFont(new Font("Arial", Font.PLAIN, 12));

    JLabel price = new JLabel("₱ " + rent);
    price.setFont(new Font("Arial", Font.BOLD, 12));

    infoPanel.add(title);
    infoPanel.add(Box.createVerticalStrut(3));
    infoPanel.add(location);
    infoPanel.add(Box.createVerticalStrut(3));
    infoPanel.add(price);

    panel.add(infoPanel, BorderLayout.CENTER);

    // 🔷 ACTION BUTTONS
    JPanel bottomPanel = new JPanel(new FlowLayout(FlowLayout.RIGHT, 10, 5));
    bottomPanel.setBackground(Color.WHITE);

    ImageIcon deleteIcon = new ImageIcon(getClass().getResource("/images/deleteIcon.png"));
    ImageIcon editIcon = new ImageIcon(getClass().getResource("/images/editIcon.png"));

    JLabel deleteLabel = new JLabel(new ImageIcon(
        deleteIcon.getImage().getScaledInstance(18, 18, Image.SCALE_SMOOTH)
    ));

    JLabel editLabel = new JLabel(new ImageIcon(
        editIcon.getImage().getScaledInstance(18, 18, Image.SCALE_SMOOTH)
    ));

    deleteLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    editLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    
    deleteLabel.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
        deleteRoomCard(roomId, dormId, locationId);
    }
        });

    bottomPanel.add(editLabel);
    bottomPanel.add(deleteLabel);

    panel.add(bottomPanel, BorderLayout.SOUTH);

    return panel;
}
    
    private void showDormPage(int page) {
    dormPanel.removeAll();

    currentPage = page;

    // 💥 main layout
    dormPanel.setLayout(new BorderLayout());

    JPanel gridPanel = new JPanel(new GridLayout(2, 2, 12, 12));
    gridPanel.setBackground(new Color(153, 204, 255));
    gridPanel.setBorder(BorderFactory.createEmptyBorder(12, 12, 12, 12));

    // ✅ ADD DORM CARD FIRST
    gridPanel.add(createAddDormCard());

    int start = (page - 1) * roomsPerPage;
    int end = Math.min(start + roomsPerPage, roomList.size());

    for (int i = start; i < end; i++) {
        Object[] data = roomList.get(i);

        int id = (int) data[0];
        String roomNo = (String) data[1];
        String dorm = (String) data[2];
        double rent = (double) data[3];
        String brgy = (String) data[4];
        String municipality = (String) data[5];

        gridPanel.add(createDormCard(id, roomNo, dorm, rent, brgy, municipality));
    }

    // 🔷 NAVIGATION
    JPanel navPanel = new JPanel();

    JButton prev = new JButton("Previous");
    JButton next = new JButton("Next");

    prev.setEnabled(page > 1);
    next.setEnabled(end < roomList.size());

    prev.addActionListener(e -> showDormPage(currentPage - 1));
    next.addActionListener(e -> showDormPage(currentPage + 1));

    navPanel.add(prev);
    navPanel.add(next);

    // 💥 attach
    dormPanel.add(gridPanel, BorderLayout.CENTER);
    dormPanel.add(navPanel, BorderLayout.SOUTH);

    dormPanel.revalidate();
    dormPanel.repaint();
}
    private JPanel createDormCard(int roomId, String roomNo, String dormName, double rent, String brgy, String municipality) {
    JPanel panel = new JPanel();
    panel.setPreferredSize(new Dimension(220, 220));
    panel.setLayout(new BorderLayout());
    panel.setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY));
    panel.setBackground(Color.WHITE);

    int cardWidth = 180;
    int cardHeight = 200;
    int imageWidth = 224;
    int imageHeight = (int)(cardHeight * 0.7);

    // 🔷 IMAGE
    JLabel imgLabel = new JLabel();
    imgLabel.setHorizontalAlignment(JLabel.CENTER);

    ImageIcon img = getFirstImage(roomId);
    if (img != null) {
        Image scaled = img.getImage().getScaledInstance(imageWidth, imageHeight, Image.SCALE_SMOOTH);
        imgLabel.setIcon(new ImageIcon(scaled));
    }
    imgLabel.setPreferredSize(new Dimension(cardWidth, imageHeight));
    panel.add(imgLabel, BorderLayout.NORTH);

    // 🔷 INFO
    JPanel infoPanel = new JPanel();
    infoPanel.setLayout(new BoxLayout(infoPanel, BoxLayout.Y_AXIS));
    infoPanel.setBackground(Color.WHITE);
    infoPanel.setBorder(BorderFactory.createEmptyBorder(5, 10, 5, 10));

    JLabel title = new JLabel("Room " + roomNo + ", " + dormName);
    title.setFont(new Font("Arial", Font.BOLD, 13));

    JLabel location = new JLabel(brgy + ", " + municipality);
    location.setFont(new Font("Arial", Font.PLAIN, 12));

    JLabel price = new JLabel("₱ " + rent);
    price.setFont(new Font("Arial", Font.BOLD, 12));

    infoPanel.add(title);
    infoPanel.add(Box.createVerticalStrut(3));
    infoPanel.add(location);
    infoPanel.add(Box.createVerticalStrut(3));
    infoPanel.add(price);

    panel.add(infoPanel, BorderLayout.CENTER);

    // 🔷 BOTTOM BUTTON (CENTERED)
    JPanel bottomPanel = new JPanel(new FlowLayout(FlowLayout.CENTER));
    bottomPanel.setBackground(Color.WHITE);

    JButton seeMoreBtn = new JButton("See more");

    seeMoreBtn.addActionListener(e -> {
        // 👉 you can open another frame or dialog here
        JOptionPane.showMessageDialog(null, "Room ID: " + roomId);
    });

    bottomPanel.add(seeMoreBtn);

    panel.add(bottomPanel, BorderLayout.SOUTH);

    return panel;
}
    
    private JPanel createAddRoomCard() {
    JPanel panel = new JPanel();
    panel.setPreferredSize(new Dimension(200, 200));
    panel.setLayout(new BorderLayout());
    panel.setBorder(BorderFactory.createDashedBorder(Color.GRAY));

    JLabel addLabel = new JLabel("+ Add Room");
    addLabel.setHorizontalAlignment(JLabel.CENTER);
    addLabel.setFont(new Font("Arial", Font.BOLD, 14));

    panel.add(addLabel, BorderLayout.CENTER);

    panel.setCursor(new Cursor(Cursor.HAND_CURSOR));

    panel.addMouseListener(new MouseAdapter() {
        public void mouseClicked(MouseEvent e) {
            AddRoom ar = new AddRoom(username);
            ar.setVisible(true);
            ar.pack();
            ar.setLocationRelativeTo(null);
            ar.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            dispose();
        }
    });

    return panel;
}
    private JPanel createAddDormCard() {
    JPanel panel = new JPanel();
    panel.setPreferredSize(new Dimension(200, 200));
    panel.setLayout(new BorderLayout());
    panel.setBorder(BorderFactory.createDashedBorder(Color.GRAY));

    JLabel label = new JLabel("+ Add Room");
    label.setHorizontalAlignment(JLabel.CENTER);
    label.setFont(new Font("Arial", Font.BOLD, 14));

    panel.add(label, BorderLayout.CENTER);

    panel.setCursor(new Cursor(Cursor.HAND_CURSOR));

    panel.addMouseListener(new MouseAdapter() {
        public void mouseClicked(MouseEvent e) {
            AddRoom ar = new AddRoom(username);
            ar.setVisible(true);
            ar.pack();
            ar.setLocationRelativeTo(null);
            ar.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            dispose();
        }
    });

    return panel;
}
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accountSettingPanel;
    private javax.swing.JButton accountSettingsBtn4;
    private javax.swing.JButton addAccountBtn4;
    private javax.swing.JPanel dormPanel;
    private javax.swing.JButton dormitoriesBtn4;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JButton informationBtn4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JLabel landlordName4;
    private javax.swing.JButton logoutBtn4;
    private javax.swing.JButton manageRoomBtn4;
    private javax.swing.JPanel parentPanel;
    private javax.swing.JPanel roomManagementPanel;
    // End of variables declaration//GEN-END:variables
}
