import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;


public class StudentHomePage extends javax.swing.JFrame {
    Connection con;
    private int currentPage = 1;
    private int roomsPerPage = 4;
    private List<Object[]> filteredList = new ArrayList<>();
    private List<Object[]> roomList = new ArrayList<>();
    
    private JComboBox<String> municipalityDropdown;
private JTextField searchField;
private JComboBox<String> priceOrderDropdown;
private JLabel orderIcon;

private JTextField minPriceField;
private JTextField maxPriceField;

private JLabel searchIcon;
private JLabel allLabel;

private boolean ascending = true;

    public StudentHomePage() {
        initComponents();
        
        con = MyConnection.getConnection();
        

        displayAllRooms();
        topPanel.setLayout(new FlowLayout(FlowLayout.LEFT, 10, 10));

        JTextField searchField = new JTextField(10);
        JTextField locationField = new JTextField(10);
        JTextField minPriceField = new JTextField(5);
        JTextField maxPriceField = new JTextField(5);

        JButton searchBtn = new JButton("Search");
        JButton resetBtn = new JButton("Reset");

// labels (optional but cleaner)
        topPanel.add(new JLabel("Search:"));
        topPanel.add(searchField);

        topPanel.add(new JLabel("Location:"));
        topPanel.add(locationField);

        topPanel.add(new JLabel("Min ₱:"));
        topPanel.add(minPriceField);

        topPanel.add(new JLabel("Max ₱:"));
        topPanel.add(maxPriceField);

        topPanel.add(searchBtn);
        
        topPanel.add(resetBtn);
        
        setupTopPanelUI();
        loadMunicipalities();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        topPanel = new javax.swing.JPanel();
        centerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(72, 133, 199));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText(" DorFi");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("<");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout centerPanelLayout = new javax.swing.GroupLayout(centerPanel);
        centerPanel.setLayout(centerPanelLayout);
        centerPanelLayout.setHorizontalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        centerPanelLayout.setVerticalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 582, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Browse available rooms and find the one that fits you best.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 666, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(centerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(centerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        RoleSelection rs = new RoleSelection();
        rs.setVisible(true);
        rs.pack();
        rs.setLocationRelativeTo(null);
        rs.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked
    
   private void setupTopPanelUI() {

    topPanel.removeAll();
    topPanel.setLayout(new BorderLayout());
    topPanel.setBackground(new Color(153, 204, 255));

    // 🔷 TOP ROW
    JPanel topRow = new JPanel(new BorderLayout(10, 0));
    topRow.setOpaque(false);

    municipalityDropdown = new JComboBox<>();
    municipalityDropdown.setPreferredSize(new Dimension(180, 35));

    searchField = new JTextField();
    searchField.setPreferredSize(new Dimension(250, 35));

    topRow.add(municipalityDropdown, BorderLayout.EAST);
    topRow.add(searchField, BorderLayout.CENTER);

    // 🔷 BOTTOM ROW
    JPanel bottomRow = new JPanel(new BorderLayout());
    bottomRow.setOpaque(false);

    // LEFT SIDE
    JPanel leftPanel = new JPanel(new FlowLayout(FlowLayout.LEFT, 10, 5));
    leftPanel.setOpaque(false);
    
    JLabel priceOrderDropdown = new JLabel("Price");
    
    priceOrderDropdown.setPreferredSize(new Dimension(80, 30));

    ImageIcon icon = new ImageIcon(getClass().getResource("/images/downIcon.png"));
    Image img = icon.getImage().getScaledInstance(20, 20, Image.SCALE_SMOOTH);
    orderIcon = new JLabel(new ImageIcon(img));

    orderIcon.setCursor(new Cursor(Cursor.HAND_CURSOR));
    orderIcon.addMouseListener(new MouseAdapter() {
        public void mouseClicked(MouseEvent e) {
            toggleSortIcon();
        }
    });

    minPriceField = new JTextField(5);
    maxPriceField = new JTextField(5);

    leftPanel.add(priceOrderDropdown);
    leftPanel.add(orderIcon);
    leftPanel.add(new JLabel("Min:"));
    leftPanel.add(minPriceField);
    leftPanel.add(new JLabel("Max:"));
    leftPanel.add(maxPriceField);

    // RIGHT SIDE
    JPanel rightPanel = new JPanel(new FlowLayout(FlowLayout.RIGHT, 10, 5));
    rightPanel.setOpaque(false);

    ImageIcon searchImg = new ImageIcon(getClass().getResource("/images/searchIcon.png"));
    Image scaledSearch = searchImg.getImage().getScaledInstance(20, 20, Image.SCALE_SMOOTH);
        searchIcon = new JLabel(new ImageIcon(scaledSearch));
    searchIcon.setCursor(new Cursor(Cursor.HAND_CURSOR));

    allLabel = new JLabel("All");
    allLabel.setForeground(Color.BLUE);
    allLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));

    rightPanel.add(searchIcon);
    rightPanel.add(allLabel);

    bottomRow.add(leftPanel, BorderLayout.WEST);
    bottomRow.add(rightPanel, BorderLayout.EAST);

    // 🔷 ADD TO MAIN
    topPanel.add(topRow, BorderLayout.NORTH);
    topPanel.add(bottomRow, BorderLayout.SOUTH);

    // 🔥 ACTIONS
    searchIcon.addMouseListener(new MouseAdapter() {
        public void mouseClicked(MouseEvent e) {
            applyFilters();
        }
    });

    allLabel.addMouseListener(new MouseAdapter() {
        public void mouseClicked(MouseEvent e) {
            resetFilters();
        }
    });

    topPanel.revalidate();
    topPanel.repaint();
}
   private void loadMunicipalities() {
    try {
        String query = "SELECT DISTINCT municipality FROM location_table";
        PreparedStatement ps = con.prepareStatement(query);
        ResultSet rs = ps.executeQuery();

        municipalityDropdown.addItem("All");

        while (rs.next()) {
            municipalityDropdown.addItem(rs.getString("municipality"));
        }

    } catch (Exception e) {
        e.printStackTrace();
    }
}
   private void toggleSortIcon() {
    ascending = !ascending;

    String path = ascending ? "/images/upIcon.png" : "/images/downIcon.png";
    orderIcon.setIcon(new ImageIcon(getClass().getResource(path)));
}
   private void applyFilters() {
    String keyword = searchField.getText().toLowerCase();
    String selectedMunicipality = (String) municipalityDropdown.getSelectedItem();

    double min = 0;
    double max = Double.MAX_VALUE;

    try {
        if (!minPriceField.getText().isEmpty())
            min = Double.parseDouble(minPriceField.getText());

        if (!maxPriceField.getText().isEmpty())
            max = Double.parseDouble(maxPriceField.getText());

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Invalid price input");
        return;
    }

    filteredList.clear();

    for (Object[] room : roomList) {
        String roomNo = ((String) room[1]).toLowerCase();
        String dorm = ((String) room[2]).toLowerCase();
        double rent = (double) room[3];
        String municipality = ((String) room[5]);

        boolean matchKeyword = roomNo.contains(keyword) || dorm.contains(keyword);
        boolean matchMunicipality = selectedMunicipality.equals("All") ||
                                   municipality.equals(selectedMunicipality);
        boolean matchPrice = rent >= min && rent <= max;

        if (matchKeyword && matchMunicipality && matchPrice) {
            filteredList.add(room);
        }
    }

    // 🔥 SORT
    filteredList.sort((a, b) -> {
        double r1 = (double) a[3];
        double r2 = (double) b[3];
        return ascending ? Double.compare(r1, r2) : Double.compare(r2, r1);
    });

    showPage(1);
}
   private void resetFilters() {
    searchField.setText("");
    minPriceField.setText("");
    maxPriceField.setText("");
    municipalityDropdown.setSelectedIndex(0);

    filteredList.clear();
    filteredList.addAll(roomList);

    showPage(1);
}
    
    private void displayAllRooms() {
    roomList.clear();

    try {
        String query = "SELECT r.room_id, r.room_number, r.rent, d.dorm_name, l.brgy, l.municipality " +
                       "FROM room_table r " +
                       "JOIN dorm_building d ON r.dorm_id = d.dorm_id " +
                       "JOIN location_table l ON d.location_id = l.location_id";

        PreparedStatement ps = con.prepareStatement(query);
        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            roomList.add(new Object[]{
                rs.getInt("room_id"),
                rs.getString("room_number"),
                rs.getString("dorm_name"),
                rs.getDouble("rent"),
                rs.getString("brgy"),
                rs.getString("municipality")
            });
        }

    } catch (SQLException e) {
        e.printStackTrace();
    }

    filteredList.clear();
    filteredList.addAll(roomList);
    showPage(1);
}
    private void showPage(int page) {
    centerPanel.removeAll();

    currentPage = page;

    centerPanel.setLayout(new BorderLayout());

    JPanel gridPanel = new JPanel(new GridLayout(2, 2, 12, 12));
    gridPanel.setBackground(new Color(153, 204, 255));
    gridPanel.setBorder(BorderFactory.createEmptyBorder(12, 12, 12, 12));

    int start = (page - 1) * roomsPerPage;
    int end = Math.min(start + roomsPerPage, filteredList.size());

    for (int i = start; i < end; i++) {
        Object[] data = filteredList.get(i);

        gridPanel.add(createRoomCard(
                (int) data[0],
                (String) data[1],
                (String) data[2],
                (double) data[3],
                (String) data[4],
                (String) data[5]
        ));
    }

    JPanel navPanel = new JPanel();

    JButton prev = new JButton("Previous");
    JButton next = new JButton("Next");

    prev.setEnabled(page > 1);
    next.setEnabled(end < filteredList.size());

    prev.addActionListener(e -> showPage(currentPage - 1));
    next.addActionListener(e -> showPage(currentPage + 1));

    navPanel.add(prev);
    navPanel.add(next);

    centerPanel.add(gridPanel, BorderLayout.CENTER);
    centerPanel.add(navPanel, BorderLayout.SOUTH);

    centerPanel.revalidate();
    centerPanel.repaint();
}
    private JPanel createRoomCard(int roomId, String roomNo, String dormName,
                              double rent, String brgy, String municipality) {

    JPanel panel = new JPanel();
    panel.setPreferredSize(new Dimension(220, 220));
    panel.setLayout(new BorderLayout());
    panel.setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY));
    panel.setBackground(Color.WHITE);

    int imageHeight = 140;

    // 🔷 IMAGE
    JLabel imgLabel = new JLabel();
    imgLabel.setHorizontalAlignment(JLabel.CENTER);

    ImageIcon img = getFirstImage(roomId);
    if (img != null) {
        Image scaled = img.getImage().getScaledInstance(224, imageHeight, Image.SCALE_SMOOTH);
        imgLabel.setIcon(new ImageIcon(scaled));
    }

    imgLabel.setPreferredSize(new Dimension(220, imageHeight));
    panel.add(imgLabel, BorderLayout.NORTH);

    // 🔷 INFO
    JPanel infoPanel = new JPanel();
    infoPanel.setLayout(new BoxLayout(infoPanel, BoxLayout.Y_AXIS));
    infoPanel.setBackground(Color.WHITE);
    infoPanel.setBorder(BorderFactory.createEmptyBorder(5, 10, 5, 10));

    JLabel title = new JLabel("Room " + roomNo + ", " + dormName);
    title.setFont(new Font("Arial", Font.BOLD, 13));

    JLabel location = new JLabel(brgy + ", " + municipality);
    JLabel price = new JLabel("₱ " + rent);

    infoPanel.add(title);
    infoPanel.add(Box.createVerticalStrut(3));
    infoPanel.add(location);
    infoPanel.add(Box.createVerticalStrut(3));
    infoPanel.add(price);

    panel.add(infoPanel, BorderLayout.CENTER);

    // 🔷 BUTTON
    JPanel bottomPanel = new JPanel(new FlowLayout(FlowLayout.CENTER));
    bottomPanel.setBackground(Color.WHITE);

    JButton viewBtn = new JButton("See more");

    viewBtn.addActionListener(e -> {
        JOptionPane.showMessageDialog(null, "Room ID: " + roomId);
    });

    bottomPanel.add(viewBtn);

    panel.add(bottomPanel, BorderLayout.SOUTH);

    return panel;
}
    private ImageIcon getFirstImage(int roomId) {
    try {
        String q = "SELECT room_photo FROM room_image WHERE room_id = ? LIMIT 1";
        PreparedStatement ps = con.prepareStatement(q);
        ps.setInt(1, roomId);

        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            return new ImageIcon(rs.getString("room_photo"));
        }

    } catch (Exception e) {
        e.printStackTrace();
    }
    return null;
}
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentHomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel centerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
